### ISSUE TITLE
Question regarding X509 certificates

### ISSUE THREAD

**Issue by borillo** [polycrypt/polycrypt#1]
Hi,

Congratulations!! Your project rocks :)

We are maintaining a Java based CryptoApplet for digitally sign content in the browser using a personal X509 certificate stored in the browser store, SO or smartcard reader.

Do you think that there is any chance or future integration to move from Java applets to a pure JavaScript approach?

Best regards,
  Ricardo

**Comment by bifurcation** [comment]
Hi Ricardo,

The answer is: It depends on what your security requirements are.

You can definitely sign content and even create certificates using PolyCrypt.  You just need an ASN.1 library to handle that part.  I'm actually working on a demo right now that creates a self-signed certificate; I'll try to remember to let you know when that's ready.  

So using PolyCrypt, you could probably do what you're doing now, with a key/cert that would be stored in web storage, as opposed to the browser cert store.  PolyCrypt would give your application access to the key pair in wrapped form, where the wrapping is done using a symmetric key stored in localStorage under the origin "http://polycrypt.net".  You can then store the wrapped key in your app's localStorage, IndexedDB, etc.  

This scheme doesn't buy you much security, though, since someone with access to the disk can still decrypt the wrapped key.  And it doesn't get you the benefits of having things in the browser, e.g., the ability to do TLS client authentication.

I don't think that PolyCrypt is likely to get access to browser-backed or smart-card-backed keys.  For that you would need real reach into the hardware, which PolyCrypt just doesn't have because it's pure JS.  However, the whole idea of PolyCrypt is that you could go ahead and start writing your application code using PolyCrypt, then once the browser support is there, you can switch over to that to get the real hardware-backed keys.  

Hope this helps,
--Richard

**Comment by borillo** [comment]
Hi Richard,

Your approach to locally store digital certificates seems very interesting, but our scenario is more related to the interaction with the browser and smartcard storages.

I have seen some work to this approach in the DOMCrypt implementation for Firefox:

http://domcrypt.org/

I'm not sure if PolyCrypt is or will be aligned with this goals, but definitely it seems the future of our CryptoApplet :)

Best regards

**Comment by bifurcation** [comment]
Indeed, the DOMCrypt approach to extending the browser is the ultimate way to go.  The idea of PolyCrypt is to let you develop application code that uses the API that the browser will expose, without having to have an upgraded browser.  Not something that you would want to deploy in production, but it at least lets you get prepared for when browsers to get upgraded!
